### ISSUE TITLE
Duplicate SVG tags

### ISSUE THREAD

**Issue by t4t5** [codefeathers/rollup-plugin-svelte-svg#5]
It seems like this plugin always generates a parent `<svg>` wrapping the original.

**Example:**
<img width="823" alt="Screenshot 2020-03-08 at 06 10 52" src="https://user-images.githubusercontent.com/2598660/76157033-beac9900-6103-11ea-9e7c-9c51277eac58.png">

While it seems like it still renders in the browser, it makes it much more difficult to adjust things like the `width` and `height`, since you're just editing the container SVG instead of the "real" one.

**Comment by MKRhere** [comment]
I'm aware of this issue. I just need to strip the actual svg tag from the source. I wasn't comfortable with bundling a full XML parser and RegExp isn't a good way to parse XML.

I will fix it soon, since it seems this package is being used quite a bit outside our company. Thanks for bringing this up!

**Comment by joycollector** [comment]
Should be fixed by #6

**Comment by MKRhere** [comment]
Closed in #6 

Released as `0.2.2` on npm
